version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
  
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
  
  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
    volumes:
      - ./logs:/usr/src/app/logs
  
  plot:
    build:
      context: ./plot
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
      - metric
    volumes:
      - ./logs:/usr/src/app/logs
