version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always

  db_push:
    build:
      context: ./db_push
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./data:/usr/src/app/data
